### ISSUE TITLE
Can't find scraped defs

### ISSUE THREAD

**Issue by coding-bunny** [nodenv/node-build-update-defs#49]
Hello,

I'm trying to install Node 12.18.0 on my system, but I can't get the tools to actually find the version.

Using `nodenv install -list` shows me the that 12.16.3 is the final version for  me. So I looked up the documentation on how to get the most recent versions.
I've upgraded `nodenv` and `node-build` using Homebrew, and they are on the latest version.

When I ran `nodenv update-version-defs` I can see in the output it wrote the defintions for 12.18.0, but I still cannot install it, the install command keeps telling me it can't find the version and that I should upgrade 

```
brew update && brew upgrade node-build
Updated 1 tap (homebrew/cask).
==> Updated Casks
rubymine
Updating Homebrew...
Warning: node-build 4.8.3 already installed
```

```
nodenv install 12.18.0                
node-build: definition not found: 12.18.0

See all available versions with `nodenv install --list'.

If the version you need is missing, try upgrading node-build:

  brew update && brew upgrade node-build
```

```
nodenv update-version-defs            
nodenv: version `12.18.0' is not installed (set by /Users/olivar/RubymineProjects/customink-for-business/.node-version)
```

**Comment by coding-bunny** [comment]
so basically you're telling me that I was impatient :D

I've danced around the problem for now with `nvm` instead as I needed it urgently for some docker builds, but good to know how the process works :)
And I think I have it all installed with Homebrew actually. Might swap that around to direct git installations.

I'll close the issue for now as it got resolved with a temporary explanation.
Thank you for the detailed info :)

**Comment by jasonkarns** [comment]
> so basically you're telling me that I was impatient :D

lol, everyone has different needs!

The reason that the git installation (of the plugin) is easier is because the nodenv-install plugin automatically adds all git-installed plugins' `share/node-build` directories to the `NODE_BUILD_DEFINITIONS` variable.

https://github.com/nodenv/node-build/blob/8c24f8490e2672b42442200eda2910e96bc76df0/bin/nodenv-install#L33-L35

So if the `node-build-update-defs` plugin is installed _outside_ of `$(nodenv root)` (which is the case when installed via npm or homebrew), then nodenv-install is unable to find the plugin's share/node-build directory. Which means that any definitions written by the plugin won't be found.

The solution is to manually add the plugins' share/node-build directory to the variable, something like (for homebrew):

```sh
export NODE_BUILD_DEFINITIONS="$(brew --prefix node-build-update-defs)/share/node-build"
```

**Comment by coding-bunny** [comment]
Thanks, will bookmark this for future usage :)
